name: Defang Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Whether to deploy up or down"
        required: true
        default: "up"
        type: choice
        options:
          - up
          - down
      stack:
        description: "The stack to deploy up or down. (Leave blank for default)"
        default: "production"

jobs:
  defang:
    name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    concurrency:
      cancel-in-progress: false
      group: deploy-elysia-demo-1-${{ github.event.inputs.stack || 'production' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: ${{ github.event.inputs.action || 'up' }}
          project: elysia-demo-1
          stack: ${{ github.event.inputs.stack || 'production' }}

      - name: Deployment Summary
        uses: DefangLabs/defang-github-action@v1.4.0
        with:
          command: services
          project: elysia-demo-1
          stack: ${{ github.event.inputs.stack || 'production' }}
